# Alpine base image - 3.3 
FROM alpine:3.3

MAINTAINER Srikanth <srikanth@astau.com>

RUN apk update && apk upgrade \
  && apk add ca-certificates \
  && apk add curl \
  && apk add wget \
  && apk add bash 